image: rust:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - python build_website.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
