image: rust:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - rustup update stable && rustup default stable
    - cargo install --git https://github.com/getzola/zola.git --locked
    - zola build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
