image: rust:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  cache:
    - key:
        files:
          - config.toml
      paths:
        - ~/.cargo/bin/
        - ~/.cargo/registry/index/
        - ~/.cargo/registry/cache/
        - ~/.cargo/git/db/
  script:
    - rustup update stable && rustup default stable
    - cargo install --git https://github.com/getzola/zola.git --locked --force
    - zola build
    - echo "$KEYBASE_PROOF" > public/keybase.txt
    - 'echo "google-site-verification: google$GOOGLE_PROOF.html" > "public/google$GOOGLE_PROOF.html"'
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment: production
