name: Build my website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-docs:
    name: Build the documentation

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo files
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-stable-${{ runner.os }}-${{ github.sha }}
          restore-keys: cargo-stable-${{ runner.os }}-

      - name: Install Zola
        run: cargo install --git https://github.com/getzola/zola.git --locked --force

      - name: Build the documentation
        run: zola build

      - name: Add Keybase proof
        run: echo "${{ secrets.KEYBASE_PROOF }}" > public/keybase.txt

      - name: Add Google proof
        # Use the GOOGLE_PROOF secret to add a Google proof file to the public directory
        run: 'echo "google-site-verification: google${{ secrets.GOOGLE_PROOF }}.html" > "public/google${{ secrets.GOOGLE_PROOF }}.html"'

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: Deploy to GitHub Pages
    needs: build-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
